openapi: 3.0.1
info:
  title: SampleDataServiceAPI
  description: API Definition of SampleDataServiceAPI
  version: 1.0.0
servers:
- url: http://localhost:8290/sample/dss
paths:
  /:
    get:
      responses:
        default:
          description: Default response
    post:
      responses:
        default:
          description: Default response
