openapi: 3.0.1
info:
  title: SampleDataMapperAPI
  description: API Definition of SampleDataMapperAPI
  version: 1.0.0
servers:
- url: http://localhost:8290/sample/datamapper
paths:
  /:
    get:
      responses:
        default:
          description: Default response
    post:
      responses:
        default:
          description: Default response
