openapi: 3.0.1
info:
  title: SampleIterateAPI
  description: API Definition of SampleIterateAPI
  version: 1.0.0
servers:
- url: http://localhost:8290/iterate
paths:
  /:
    post:
      responses:
        default:
          description: Default response
