openapi: 3.0.1
info:
  title: SampleClassMediatorAPI
  description: API Definition of SampleClassMediatorAPI
  version: 1.0.0
servers:
- url: http://localhost:8290/class/test
paths:
  /:
    get:
      responses:
        default:
          description: Default response
